# These are supported funding model platforms

github: [chakravala]
patreon: dreamscatter
liberapay: chakravala
open_collective: grassmannjl
ko_fi: # Replace with a single Ko-fi username
tidelift: "julia/Grassmann"
otechie: # Replace with a single Otechie username
custom: https://music.crucialflow.com
